Setup poetry autocompletion

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -62,6 +62,34 @@ install_poetry() {
     echo Consider upgrading to a later version.
     echo https://github.com/asdf-community/asdf-poetry/issues/10
   fi
+
+  if [ $config_vercomp == "ge" ]; then
+    if echo "$SHELL" | grep -q "bash"; then
+      echo "Detected default shell bash"
+      echo "Setting up autocompletion for bash..."
+      "$install_path"/bin/poetry completions bash >~/.bash_completion
+    elif echo "$SHELL" | grep -q "zsh"; then
+      if [ ! -d "$HOME/.zfunc/" ]; then
+        mkdir -p ~/.zfunc
+      fi
+      if [ ! -f "$HOME/.zfunc/_poetry" ]; then
+        echo "Detected default shell zsh"
+        echo "Setting up autocompletion for zsh..."
+        "$install_path"/bin/poetry completions zsh >~/.zfunc/_poetry
+      fi
+      grep -qxF 'fpath+=~/.zfunc' ~/.zshrc || echo "fpath+=~/.zfunc" >>~/.zshrc
+      grep -qxF 'autoload -Uz compinit && compinit' ~/.zshrc || echo "autoload -Uz compinit && compinit" >>~/.zshrc
+    elif echo "$SHELL" | grep -q "fish"; then
+      echo "Detected default shell fish"
+      echo "Setting up autocompletion for fish..."
+      "$install_path"/bin/poetry completions fish >~/.config/fish/completions/poetry.fish
+    else
+      echo "Warning: Could not detect BASH, ZSH or FISH."
+      echo "Could not complete autocompletion setup"
+    fi
+  else
+    echo "Warning: Poetry versions prior to 1.2.0 will not have autocompletion"
+  fi
 }
 
 install_poetry "$ASDF_INSTALL_TYPE" "$ASDF_INSTALL_VERSION" "$ASDF_INSTALL_PATH"
